// Code generated by goctl. DO NOT EDIT.
// Source: spu.proto

package server

import (
	"context"

	"goods_center/rpc/internal/logic"
	"goods_center/rpc/internal/svc"
	"goods_center/rpc/spu"
)

type SpuServer struct {
	svcCtx *svc.ServiceContext
	spu.UnimplementedSpuServer
}

func NewSpuServer(svcCtx *svc.ServiceContext) *SpuServer {
	return &SpuServer{
		svcCtx: svcCtx,
	}
}

func (s *SpuServer) GetSpuInfo(ctx context.Context, in *spu.GetSpuInfoRequest) (*spu.GetSpuInfoResponse, error) {
	l := logic.NewGetSpuInfoLogic(ctx, s.svcCtx)
	return l.GetSpuInfo(in)
}
