// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	orders "orders/api/internal/handler/orders"
	"orders/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/info/get",
				Handler: orders.GetOrderGoodsInfoHandler(serverCtx),
			},
		},
	)
}
