// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: spu.proto

package spu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSpuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SpuId string `protobuf:"bytes,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
}

func (x *GetSpuInfoRequest) Reset() {
	*x = GetSpuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuInfoRequest) ProtoMessage() {}

func (x *GetSpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_spu_proto_rawDescGZIP(), []int{0}
}

func (x *GetSpuInfoRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetSpuInfoRequest) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

type GetSpuInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuInfo *SpuInfo `protobuf:"bytes,1,opt,name=SpuInfo,proto3" json:"SpuInfo,omitempty"`
}

func (x *GetSpuInfoResponse) Reset() {
	*x = GetSpuInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpuInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpuInfoResponse) ProtoMessage() {}

func (x *GetSpuInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpuInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSpuInfoResponse) Descriptor() ([]byte, []int) {
	return file_spu_proto_rawDescGZIP(), []int{1}
}

func (x *GetSpuInfoResponse) GetSpuInfo() *SpuInfo {
	if x != nil {
		return x.SpuInfo
	}
	return nil
}

type SpuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId           string `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                                   // 店铺id
	SpuId           string `protobuf:"bytes,3,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`                                   // 商品id
	SpuType         string `protobuf:"bytes,4,opt,name=spu_type,json=spuType,proto3" json:"spu_type,omitempty"`                             // 商品类型(关联t_spu_type)
	GoodsCategoryId string `protobuf:"bytes,5,opt,name=goods_category_id,json=goodsCategoryId,proto3" json:"goods_category_id,omitempty"`   // 商品分类id
	GoodsName       string `protobuf:"bytes,6,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`                       // 商品名称
	GoodsImg        string `protobuf:"bytes,7,opt,name=goods_img,json=goodsImg,proto3" json:"goods_img,omitempty"`                          // 商品封面图（默认封面图）
	Price           int32  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`                                               // 商品最低价
	PriceLine       int32  `protobuf:"varint,9,opt,name=price_line,json=priceLine,proto3" json:"price_line,omitempty"`                      // 划线价
	GoodsTag        string `protobuf:"bytes,10,opt,name=goods_tag,json=goodsTag,proto3" json:"goods_tag,omitempty"`                         // 商品标签
	SaleStatus      int32  `protobuf:"varint,11,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`                  // 上架状态： 0下架 1上架 2（定时上架还未上架阶段）待上架 4强制下架 5封禁
	SaleAt          string `protobuf:"bytes,12,opt,name=sale_at,json=saleAt,proto3" json:"sale_at,omitempty"`                               // 实际上架的时间
	IsDisplay       int32  `protobuf:"varint,13,opt,name=is_display,json=isDisplay,proto3" json:"is_display,omitempty"`                     // 是否显示：0否(隐藏状态) 1是(显示状态)
	LimitPurchase   int32  `protobuf:"varint,14,opt,name=limit_purchase,json=limitPurchase,proto3" json:"limit_purchase,omitempty"`         // 限购数量
	StockDeductMode int32  `protobuf:"varint,15,opt,name=stock_deduct_mode,json=stockDeductMode,proto3" json:"stock_deduct_mode,omitempty"` // 扣库存方式：0付款减库存 1拍下减库存
	IsDeleted       int32  `protobuf:"varint,16,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`                     // 0正常 1已删除
	CreatedAt       string `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                      // 创建时间
	UpdatedAt       string `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                      // 更新时间，有修改自动更新
}

func (x *SpuInfo) Reset() {
	*x = SpuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuInfo) ProtoMessage() {}

func (x *SpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuInfo.ProtoReflect.Descriptor instead.
func (*SpuInfo) Descriptor() ([]byte, []int) {
	return file_spu_proto_rawDescGZIP(), []int{2}
}

func (x *SpuInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpuInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SpuInfo) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

func (x *SpuInfo) GetSpuType() string {
	if x != nil {
		return x.SpuType
	}
	return ""
}

func (x *SpuInfo) GetGoodsCategoryId() string {
	if x != nil {
		return x.GoodsCategoryId
	}
	return ""
}

func (x *SpuInfo) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *SpuInfo) GetGoodsImg() string {
	if x != nil {
		return x.GoodsImg
	}
	return ""
}

func (x *SpuInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SpuInfo) GetPriceLine() int32 {
	if x != nil {
		return x.PriceLine
	}
	return 0
}

func (x *SpuInfo) GetGoodsTag() string {
	if x != nil {
		return x.GoodsTag
	}
	return ""
}

func (x *SpuInfo) GetSaleStatus() int32 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

func (x *SpuInfo) GetSaleAt() string {
	if x != nil {
		return x.SaleAt
	}
	return ""
}

func (x *SpuInfo) GetIsDisplay() int32 {
	if x != nil {
		return x.IsDisplay
	}
	return 0
}

func (x *SpuInfo) GetLimitPurchase() int32 {
	if x != nil {
		return x.LimitPurchase
	}
	return 0
}

func (x *SpuInfo) GetStockDeductMode() int32 {
	if x != nil {
		return x.StockDeductMode
	}
	return 0
}

func (x *SpuInfo) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *SpuInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SpuInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_spu_proto protoreflect.FileDescriptor

var file_spu_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x70, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x70, 0x75,
	0x22, 0x41, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70,
	0x75, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x53, 0x70, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x70, 0x75,
	0x2e, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0xa5, 0x04, 0x0a, 0x07, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x70, 0x75, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x75, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x67, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4c,
	0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x74, 0x61, 0x67,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x61, 0x67,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x6c, 0x65, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73,
	0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x69, 0x73, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x5f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x11, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x44, 0x0a, 0x03, 0x53, 0x70, 0x75,
	0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x2e, 0x73, 0x70, 0x75, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x70, 0x75, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x73, 0x70, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spu_proto_rawDescOnce sync.Once
	file_spu_proto_rawDescData = file_spu_proto_rawDesc
)

func file_spu_proto_rawDescGZIP() []byte {
	file_spu_proto_rawDescOnce.Do(func() {
		file_spu_proto_rawDescData = protoimpl.X.CompressGZIP(file_spu_proto_rawDescData)
	})
	return file_spu_proto_rawDescData
}

var file_spu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spu_proto_goTypes = []interface{}{
	(*GetSpuInfoRequest)(nil),  // 0: spu.GetSpuInfoRequest
	(*GetSpuInfoResponse)(nil), // 1: spu.GetSpuInfoResponse
	(*SpuInfo)(nil),            // 2: spu.SpuInfo
}
var file_spu_proto_depIdxs = []int32{
	2, // 0: spu.GetSpuInfoResponse.SpuInfo:type_name -> spu.SpuInfo
	0, // 1: spu.Spu.GetSpuInfo:input_type -> spu.GetSpuInfoRequest
	1, // 2: spu.Spu.GetSpuInfo:output_type -> spu.GetSpuInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spu_proto_init() }
func file_spu_proto_init() {
	if File_spu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpuInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spu_proto_goTypes,
		DependencyIndexes: file_spu_proto_depIdxs,
		MessageInfos:      file_spu_proto_msgTypes,
	}.Build()
	File_spu_proto = out.File
	file_spu_proto_rawDesc = nil
	file_spu_proto_goTypes = nil
	file_spu_proto_depIdxs = nil
}
